import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit'; // moduls from React Toolkit
import { RootState } from '../../store/store';
import { fetchItems as fetchItemsAPI } from '../../api/api'; // importing data from API


// Interface for an item object
export interface Item {
  id: number;
  title: string;
}

// Interface for the slice state
interface ItemState {
  items: Item[];
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
}

// Initial state for the slice
const initialState: ItemState = {
  items: [],
  status: 'idle',
};

// Async thunk for fetching items
export const fetchItems = createAsyncThunk(
  'items/fetchItems',
  async () => {
    const response = await fetchItemsAPI();
    return response.data;
  }
);

// Creating a slice for items
const itemSlice = createSlice({
  name: 'items',
  initialState,
  reducers: {
    // Reducer to add an item to the state
    addItem: (state, action: PayloadAction<Item>) => {
      state.items.push(action.payload);
    },
    // Reducer to update an item
    updateItem: (state, action: PayloadAction<Item>) => {
      const index = state.items.findIndex(item => item.id === action.payload.id);
      if (index !== -1) {
        state.items[index] = action.payload;
      }
    },
    // Reducer to delete an item from the state
    deleteItem: (state, action: PayloadAction<number>) => {
      state.items = state.items.filter(item => item.id !== action.payload);
    },
  },
   // Reducers for handling async thunk actions
  extraReducers(builder) {
    builder
      .addCase(fetchItems.pending, (state) => {
        state.status = 'loading'; // Setting status to 'loading' when fetching items
      })
      .addCase(fetchItems.fulfilled, (state, action) => {
        state.status = 'succeeded'; // Setting status to 'succeeded' when fetching items is successful
        state.items = action.payload;
      })
      .addCase(fetchItems.rejected, (state) => {
        state.status = 'failed';  // Setting status to 'failed' when fetching items fails
      });
  },
});

// Exporting actions generated by createSlice
export const { addItem, updateItem, deleteItem } = itemSlice.actions;

// Selectors for accessing items state and status
export const selectItems = (state: RootState) => state.items.items;
export const selectItemsStatus = (state: RootState) => state.items.status;

// exporting reduser
export default itemSlice.reducer;

